[workspace]
resolver = "2"
members = [
  "async_rust", "functional_programming",
  "fundamentals",
  "hello_world",
  "structs_methods",
  "tdd",
]

[workspace.dependencies]
tokio = { version = "1.44.2", features = ["full"] }
